server:
  port: ${CUSTOM.SERVER.PORT:9080}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes: 
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

            #- name: CustomFilter
            - CustomFilterMitocode=MitocodeKey, MitocodeValue
            # AddRequestHeader=MitocodeKey, MitocodeValue
            # AddResponseHeader=MitocodeHeader, MitocodeHeaderValue
            # AddRequestParameter=role, ROLE_USER


            







#spring:
#  cloud:
#    gateway:
#      routes:
#        -id: user-service-data
#         uri: lb://user-service #hace refrencia al id del user service en el microservicio
#         predicates:
#          -Path=/api/user-service/** #lo deriva al user service
#          filters:
#           - StripPrefix = 3 #significa tomar como base estos 3 /api/user-service/**  1/2/3, es decir la posiciones que representaa


